# version: '3.8'
services:
  neo4j:
    image: neo4j:2025.06.2
    container_name: neo4j_user
    hostname: neo4j.server
    restart: unless-stopped
    ports:
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./conf:/conf
      - ./plugins:/plugins
      - ./import:/import
      - ./backups:/backups
      - ./ssl_certs:/etc/ssl/neo4j:ro
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*
      - NEO4J_server_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=/etc/ssl/neo4j
      - NEO4J_dbms_ssl_policy_https_private__key=key.pem
      - NEO4J_dbms_ssl_policy_https_public__certificate=cert.pem
      - NEO4J_server_bolt_tls__level=REQUIRED
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/etc/ssl/neo4j
      - NEO4J_dbms_ssl_policy_bolt_private__key=key.pem
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=cert.pem